dataset: 'tumrgbd'
grid_len:
  coarse: 2 
  middle: 0.16
  fine: 0.08
  color: 0.08

tracking:
  vis_freq: 50
  lr: 0.01   
  iters: 200

  pixels: 5000


mapping:
  every_frame: 1
  vis_freq: 50
  ckpt_freq: 500

  pixels: 5000
  iters: 60

cam:  #NOTE: intrinsic is different per scene in TUM    TODO： why?
  H: 480 
  W: 640 
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  png_depth_scale: 5000.0
  crop_edge: 0



